### ISSUE TITLE
Issue with Converting Word Embeddings to Word2Vec Format

### ISSUE THREAD

**Issue by jej127** [liangzrtvjivo/GRM#1]
Hello, I am following the instructions in README.md and have encountered an issue in the 'Word Data' section.
Specifically, I downloaded the Word2Vec background word embeddings using the command:
	wget backup.3azouz.net/gensim.w2v.skipgram.model.7z
The next step in the instructions is to change this 7z file into the word2vec format (binary = False), but I don't know how to accomplish this step.
Could you please provide more detailed instructions for this step? Any help would be greatly appreciated.

Thank you!

**Comment by liangzrtvjivo** [comment]
Thanks for your interest in our work!

After downloading the 7z file, you need to unzip it first, and load it using the code "gensim.models.word2vec.Word2Vec.load" to obtain the Word2Vec model.
Then you can change it into the word2vec format by "model.wv.save_word2vec_format(filename, binary=False)".

We'll release the preprocessed files to Google Drive in the near future so you can download them directly instead of re-preprocessing them!
