### ISSUE TITLE
About extending BERT to NER task

### ISSUE THREAD

**Issue by jej127** [liangzrtvjivo/GRM#5]
Hello, I have a question about the source code related to BERT experiments.
Specifically, I noticed that the function "merge_token" in GRM/downstream/bert/Utils/utils.py assigns -1 to the first token of an OOV word.
The number -1 corresponds to the label "DEF-FALSE" according to GRM/downstream/bert/bert_ner/dataprocess.py.

However, I'm unclear about the meaning of this label.
Could you kindly provide some clarification on what the label "DEF-FALSE" means? 
I'm curious to understand the purpose of this additional label in the context of NER evaluation.
Thank you very much for taking the time to address my inquiry. Your insights would be greatly appreciated.

**Comment by liangzrtvjivo** [comment]
Thank you for your interesting and profound question. 

In the Named Entity Recognition (NER) task, the BERT model assigns predicted labels to all the tokens of a word. For Out-of-Vocabulary (OOV) words, they have multiple tokens. When comparing the BERT model with BERT+OOV models, we encounter a challenge due to the difference in the total number of labels. BERT+OOV models predict a label for each word, while the BERT model predicts a label for each token.

To maintain consistency, we utilize the merge_token function in "downstream/bert/Utils/utils.py" to align the predictions made by the BERT model and BERT+OOV models. We set a quite high standard. Only when the BERT model can correctly predict all the tokens of a word will we consider its prediction for that word to be accurate. The "DEF-FALSE" label is an additional processing tag introduced specifically for this operation.

We appreciate your insight and are always open to further discussions on how to improve our methods.
